pipeline {
  agent any
  environment {
        VERSION = """${sh(
                returnStdout: true,
                script: 'cat version'
            )}""" 
  }
  stages {
    stage('Working'){
        steps{
                sh 'echo "Working"'
        }
    }
    stage('Pull and Lint Index.html and Dockerfile'){
        steps{
                sh 'hadolint Dockerfile'
                sh 'tidy index.html'
        }
    }
    stage('Build Docker Container and commit to ECR') {
        steps {
            sh 'sudo docker build . -t webapp:latest' 
            sh 'sudo $(aws ecr get-login --no-include-email --region us-west-2)'
            sh 'sudo docker tag webapp:latest 235447109042.dkr.ecr.us-west-2.amazonaws.com/generic-repository:${VERSION}'
            sh 'sudo docker push 235447109042.dkr.ecr.us-west-2.amazonaws.com/generic-repository:${VERSION}'
            sh 'sudo docker tag webapp:latest 235447109042.dkr.ecr.us-west-2.amazonaws.com/generic-repository:latest'
            sh 'sudo docker push 235447109042.dkr.ecr.us-west-2.amazonaws.com/generic-repository:latest'  
        }
    }
    stage('Delete old Kubernetes Pods and deploy new ones'){
        steps{
            sh 'kubectl apply -f webapp.yaml'
            sh 'kubectl apply -f webapp.service.yaml'
            sh 'kubectl set image deployment testjenkins-webapp webapp=235447109042.dkr.ecr.us-west-2.amazonaws.com/generic-repository:$VERSION'
        }
    }
  }
}
